# Most of the steps need to run on a macOS agent, so let's define it as a root property.
agents:
  queue: mac
env:
  IMAGE_ID: $IMAGE_ID

# This is the default pipeline – it will build and test the app
steps:

  #################
  # Create Prototype Builds for WP and JP
  #################
  - group: "🛠 Prototype Builds"
    steps:
      - label: "🛠 WordPress Prototype Build"
        command: ".buildkite/commands/prototype-build-wordpress.sh"
        plugins: [$CI_TOOLKIT_PLUGIN]
        if: "build.pull_request.id != null || build.pull_request.draft"
        notify:
          - github_commit_status:
              context: "WordPress Prototype Build"

      - label: "🛠 Jetpack Prototype Build"
        command: ".buildkite/commands/prototype-build-jetpack.sh"
        plugins: [$CI_TOOLKIT_PLUGIN]
        if: "build.pull_request.id != null || build.pull_request.draft"
        notify:
          - github_commit_status:
              context: "Jetpack Prototype Build"

  #################
  # Create Builds for Testing
  #################
  - group: "🛠 Builds for Testing"
    steps:
      - label: "🛠 :wordpress: Build for Testing"
        key: "build_wordpress"
        command: ".buildkite/commands/build-for-testing.sh wordpress"
        plugins:
          - $CI_TOOLKIT_PLUGIN: ~
          - nienbo/cache#v2.4.16:
              id: ruby # or ruby-3.0
              backend: tarball
              key: "v1-cache-{{ id }}-{{ runner.os }}-{{ checksum 'Gemfile.lock' }}"
              restore-keys:
                - 'v1-cache-{{ id }}-{{ runner.os }}-'
                - 'v1-cache-{{ id }}-'
              compress: false # Create tar.gz instead of .tar (Compressed) Defaults to `false`.
              tarball:
                path: '/tmp/buildkite-cache' # Defaults to /tmp with v2.4.10+
                max: 7 # Optional. Removes tarballs older than 7 days.
              paths:
                - 'vendor/bundle'
                - '~/Library/Caches/CocoaPods/'
                - '~/.cocoapods'
                - "$HOME/Library/Caches/org.swift.swiftpm"
        notify:
          - github_commit_status:
              context: "WordPress Build for Testing"

      - label: "🛠 :jetpack: Build for Testing"
        key: "build_jetpack"
        command: ".buildkite/commands/build-for-testing.sh jetpack"
        plugins: [$CI_TOOLKIT_PLUGIN]
        notify:
          - github_commit_status:
              context: "Jetpack Build for Testing"

  #################
  # Run Unit Tests
  #################
  - label: "🔬 :wordpress: Unit Tests"
    command: ".buildkite/commands/run-unit-tests.sh"
    depends_on: "build_wordpress"
    plugins: [$CI_TOOLKIT_PLUGIN]
    artifact_paths:
      - "build/results/*"
    notify:
      - github_commit_status:
          context: "Unit Tests"

  #################
  # UI Tests
  #################
  - group: "🔬 UI Tests"
    steps:
      - label: "🔬 :jetpack: UI Tests (iPhone)"
        command: .buildkite/commands/run-ui-tests.sh 'iPhone 15'
        depends_on: "build_jetpack"
        plugins: [$CI_TOOLKIT_PLUGIN]
        artifact_paths:
          - "build/results/*"
          - "build/results/crashes/*"
        notify:
          - github_commit_status:
              context: "UI Tests (iPhone)"

      - label: "🔬 :jetpack: UI Tests (iPad)"
        command: .buildkite/commands/run-ui-tests.sh 'iPad Pro 13-inch (M4)'
        depends_on: "build_jetpack"
        plugins: [$CI_TOOLKIT_PLUGIN]
        artifact_paths:
          - "build/results/*"
          - "build/results/crashes/*"
        notify:
          - github_commit_status:
              context: "UI Tests (iPad)"

  #################
  # Linters
  #################
  - group: "Linters"
    steps:
      - label: "☢️ Danger - PR Check"
        command: danger
        key: danger
        if: "build.pull_request.id != null"
        retry:
          manual:
            permit_on_passed: true
        agents:
          queue: "linter"

      - label: ":swift: SwiftLint"
        command: swiftlint
        notify:
          - github_commit_status:
              context: "SwiftLint"
        agents:
          queue: "linter"

      - label: "🧹 Lint Translations"
        command: "gplint /workdir/WordPress/Resources/AppStoreStrings.po"
        plugins:
          - docker#v3.8.0:
              image: "public.ecr.aws/automattic/glotpress-validator:1.0.0"
        agents:
          queue: "default"
        notify:
          - github_commit_status:
              context: "Lint Translations"

      - label: ":sleuth_or_spy: Lint Localized Strings Format"
        command: .buildkite/commands/lint-localized-strings-format.sh
        plugins: [$CI_TOOLKIT_PLUGIN]
